package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"parties-app/backend/database"
	"parties-app/backend/errorHandler"
	"parties-app/backend/graph/customTypes"
	"parties-app/backend/graph/generated"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, updateUser customTypes.UpdateUserArgs) (bool, error) {
	objectID, err := primitive.ObjectIDFromHex(updateUser.Query)
	if err != nil {
		errorHandler.HandleError(ctx, 401, "Invalid Query user's ID.")
	}

	err = database.UpdateUser(objectID, updateUser)
	if err != nil {
		errorHandler.HandleError(ctx, 500, "Unable to update user.")
	}

	return true, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, createUser customTypes.CreateUserArgs) (*customTypes.User, error) {
	panic(fmt.Errorf("not implemented: Signup - signup"))
}

// UpdateDate is the resolver for the updateDate field.
func (r *mutationResolver) UpdateDate(ctx context.Context, updateDate customTypes.UpdateDateInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateDate - updateDate"))
}

// RemoveDate is the resolver for the removeDate field.
func (r *mutationResolver) RemoveDate(ctx context.Context, removeDate customTypes.RemoveDateInput) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveDate - removeDate"))
}

// CreateDate is the resolver for the createDate field.
func (r *mutationResolver) CreateDate(ctx context.Context, createDate customTypes.CreateDateInput) (bool, error) {
	panic(fmt.Errorf("not implemented: CreateDate - createDate"))
}

// GetUserByID is the resolver for the getUserById field.
func (r *queryResolver) GetUserByID(ctx context.Context, id int) (*customTypes.SensoredUser, error) {
	panic(fmt.Errorf("not implemented: GetUserByID - getUserById"))
}

// GetUserByName is the resolver for the getUserByName field.
func (r *queryResolver) GetUserByName(ctx context.Context, username string) (*customTypes.SensoredUser, error) {
	panic(fmt.Errorf("not implemented: GetUserByName - getUserByName"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*customTypes.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// RequestLogin is the resolver for the requestLogin field.
func (r *queryResolver) RequestLogin(ctx context.Context, email string) (bool, error) {
	panic(fmt.Errorf("not implemented: RequestLogin - requestLogin"))
}

// ValidateOtp is the resolver for the validateOtp field.
func (r *queryResolver) ValidateOtp(ctx context.Context, code string) (*customTypes.UserRes, error) {
	panic(fmt.Errorf("not implemented: ValidateOtp - validateOtp"))
}

// Logout is the resolver for the logout field.
func (r *queryResolver) Logout(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *queryResolver) RefreshToken(ctx context.Context) (*customTypes.Tokens, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// GetEvents is the resolver for the getEvents field.
func (r *queryResolver) GetEvents(ctx context.Context, username string, duration *string) ([]*customTypes.Event, error) {
	panic(fmt.Errorf("not implemented: GetEvents - getEvents"))
}

// GetEventByID is the resolver for the getEventById field.
func (r *queryResolver) GetEventByID(ctx context.Context, username string, id string) (*customTypes.Event, error) {
	panic(fmt.Errorf("not implemented: GetEventByID - getEventById"))
}

// GetLocationData is the resolver for the getLocationData field.
func (r *queryResolver) GetLocationData(ctx context.Context, lat string, long string) (*customTypes.Location, error) {
	panic(fmt.Errorf("not implemented: GetLocationData - getLocationData"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
